### ISSUE TITLE
リプライに成功しているのにトーストメッセージで「リプライに失敗しました」と出る

### ISSUE THREAD

**Issue by natumi-kaoru** [Karatsu-5th-JHS/twisskey#39]
標記の通りです。

**Comment by 49372s** [comment]
つら

**Comment by natumi-kaoru** [comment]
リプライ成功と失敗の文言のキーが逆になってるだけだったりしますか……？（reply.dartで、`map['creatednote'] == null`ならば`rs`、そうでないならば`rf`を読み出すようになっているので）

**Comment by 49372s** [comment]
😳
そうなのかもしれん
唐津に帰ったら確認します

**Comment by 49372s** [comment]
> リプライ成功と失敗の文言のキーが逆になってるだけだったりしますか……？

その通りでした。修正します。
