### ISSUE TITLE
「♡」表示を「☆」表示にする機能 

### ISSUE THREAD

**Issue by natumi-kaoru** [Karatsu-5th-JHS/twisskey#40]
昔のTwi**erが好きな人向けに

できれば、今後「いいね（Like）  」という文言がアプリに出てくるならば、「お気に入り（Favourite） 」に変更できるように

**Comment by 49372s** [comment]
実装はできるだろうけどおそらく最初の表示が大きくバグるかも

**Comment by natumi-kaoru** [comment]
りょうかいです、closeにしておきます
issue作っておいてですが、そこまで私がほしいわけでもないので、今後誰かから要望があったらって感じで

**Comment by natumi-kaoru** [comment]
操作間違えました、すみません
